### ISSUE TITLE
diff tool with parameters missing entries

### ISSUE THREAD

**Issue by G4m30v3r** [Comcast/traffic_control#131]
when doing a compare of profiles, for example cache url.so states it belongs to profile x, but does not show up when selecting profile x.

![](https://files.slack.com/files-pri/T024VU91V-F04S7BM57/pasted_image_at_2015_05_13_03_58_pm.png)

![](https://files.slack.com/files-pri/T024VU91V-F04S7BWNX/pasted_image_at_2015_05_13_03_58_pm.png)

**Comment by G4m30v3r** [comment]
https://github.com/Comcast/traffic_control/issues/134

**Comment by mtorluemke** [comment]
@PSUdaemon has more info to add.

**Comment by PSUdaemon** [comment]
My proposed solution would be to do this in the database, either by DBI or custom query. If you do a full outer join on two aliased versions of the profile parameters table by key where value is different or NULL then you should get the exact data you want and can just print it in Perl rather than having to do some crazy data manipulation in Perl that is hard to prove correct. This will also make doing it in another language easier. So you don't have to prove it correct in Perl/Python/Go/etc.

**Comment by PSUdaemon** [comment]
More follow up. MySQL does not support full outer joins. There is some workaround that makes the query kinda messy but doable.
