### ISSUE TITLE
Error creating key and csr. Result is -1

### ISSUE THREAD

**Issue by weijian2014** [Comcast/traffic_control#1928]
Hi, I am form China.
I try add The Delivery Services as HTTPS to Traffic Ops.The Riak was worked and test by https//domain/ping display "OK" for my browser. The /opt/traffic_ops/app/conf/<environment>/riak.conf was updated to reflect the correct username and password for accessing riak too.
But try “Manage SSL keys” add a SSL key was fail:
![clipboard](https://cloud.githubusercontent.com/assets/7225360/18947688/a81bea36-8666-11e6-8691-34120079298a.png)

**Comment by dg4prez** [comment]
Did you generate before selecting "manage ssl keys?"  the generation is necessary for traffic ops and riak to create the proper files and configuration entries.

**Comment by dneuman64** [comment]
Also, do you see anything going on in the logs?  What happens if you try to generate the keys again, do you get the same error?

**Comment by dneuman64** [comment]
Hey @weijian2014, did you figure out the issue?

**Comment by weijian2014** [comment]
I'm sorry for not replying in time(National Day holiday), the issue has been resolved! Thank you very much.

**Comment by testover99** [comment]
I am seeing the same issue, can't figure out what is the issue. @weijian2014  can you please describe, how did you fix the issue?

**Comment by dneuman64** [comment]
@testover99 Usually this error is because Traffic Ops cannot talk to your riak servers.  Can you take a look at your traffic_ops logs when you try to generate keys and see what is in there?  

Also, we no longer use this repo for Traffic Control, if you are still having issues can you post on one of our mailing lists?  More info here:  http://trafficcontrol.apache.org/ask/index.html
