### ISSUE TITLE
Traffic Router: Exception JSONObject["ip"] not found.

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#341]
During load testing, we are seeing the following on the Request Router. We only have 2 caches.

During the test, there is also events like this ```REPORTED - queryTime too high (1494.000000 > 1000.000000)``` which seems to indicate but caches are going down. 

I believe that since they are marked down, there is no more A records available to be sent to clients. 

Should we have an override to report back all available A record for that zone when this condition is met? I want to make sure clients are still being sent to caches if there is no bypass URL.

```
WARN  2015-07-24T10:39:10.266 [pool-5-thread-640] com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouter - No Cache found by Geo (dns, ip=10.22.66.122, path=edge.iao-live-test.cdn1.coxlab.net)
WARN  2015-07-24T10:39:10.305 [pool-5-thread-640] com.comcast.cdn.traffic_control.traffic_router.core.ds.DeliveryService - org.json.JSONException: JSONObject["ip"] not found.
org.json.JSONException: JSONObject["ip"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at org.json.JSONObject.getString(JSONObject.java:669)
	at com.comcast.cdn.traffic_control.traffic_router.core.ds.DeliveryService.getRedirectInetRecords(DeliveryService.java:241)
	at com.comcast.cdn.traffic_control.traffic_router.core.ds.DeliveryService.getFailureDnsResponse(DeliveryService.java:225)
	at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouter.route(TrafficRouter.java:286)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.createDynamicZone(ZoneManager.java:414)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.getDynamicZone(ZoneManager.java:550)
	at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouter.getDynamicZone(TrafficRouter.java:534)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.NameServer.addAnswers(NameServer.java:92)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.NameServer.query(NameServer.java:62)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.protocol.AbstractProtocol.query(AbstractProtocol.java:118)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.protocol.UDP$UDPPacketHandler.run(UDP.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
INFO  2015-07-24T10:39:39.550 [New I/O worker #32] com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater - updated /opt/traffic_router/db/health.json
INFO  2015-07-24T10:40:36.572 [New I/O worker #1] com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater - updated /opt/traffic_router/db/health.json
```

**Comment by elsloo** [comment]
This is happening because no IPv4 bypass destination has been defined for the delivery service.  The exception prevents getRedirectInetRecords() from completing, thus no IPv6 bypass destination, nor a CNAME bypass destination would be added to the response.  Defensive code must be added to prevent this scenario to ensure that the bypass destination is returned correctly with all data.

I'm not sure that we want to just route right back to the same caches when they have been marked unavailable.  That would defeat the purpose of the health protocol.  I understand that you want the client requests to be serviced, but that's the bypass destination's purpose.  With a correctly configured (and operating) bypass destination, client requests can still be serviced.

This is related to issue #280.

**Comment by smalenfant** [comment]
What if there is no possible bypass destination?

**Comment by elsloo** [comment]
In the case of a DNS delivery service, you would get an NXDOMAIN, as no labels with the name "edge.deliveryservice.cdn.net" would exist for the dynamic zone, and an HTTP 503 response in the case of an HTTP delivery service.

If you do not have a bypass destination, you must configure your cache and delivery service health parameters in a way that will be least invasive given your expected load.  That being said, there are cases where we have seen that astats takes a while to respond when ATS is under load, and perhaps that is what is really causing the response delay during your testing.  Alternatively, if you have > 1 Traffic Monitors, the impact of this will be lessened as they will all have to agree on the state before presenting Traffic Router with the state of unavailable for a given cache or delivery service.  This is because they each have their own polling cycles and it's less likely that all Traffic Monitors will have the same response issues.

Can you check the "ttms" field in your ATS access logs and a) find the Traffic Monitor astats request(s) that correspond with the health protocol event that took them offline, and b) see if the ttms of the surround requests in the logs are similarly slow, or if only the astats request was slow.  This will allow us to understand if it's astats that's slow, or if the entire ATS instance is slow.

In the future we will be using two separate astats queries to determine health.  One will be a "fast poll" (think every second or so) that only grabs the "system" section of astats.  The fast poll should not be susceptible to the above issue, and will be used to determine the up/down availability of a given cache.  The "slow poll" will continue to be ~5 seconds and will grab all data from astats, including remap_stats.  The slow poll will be used for further cache/delivery service analysis, but will not cause the "queryTime too high" issue.

**Comment by smalenfant** [comment]
We had 2 scenarios which in all cases, we had only 2 servers configured in the same cache group.

1 - irqbalance was not installed and query time was too high for both. We resolved that.
2 - Our test load was higher than 8.5 Gbps * 2. Which means those servers are also marked offline temporarily

I believe that this should not happen with a properly sized CDN. But the problem is mostly related to the lab and also which tool we are using. Basically, our tests would bail out if the DNS would come back with no A records. I don't have control over that at this time (vendor test tool).
 
To test performance, looks like we are going to have to override at least the available bandwidth so it always returns good.
