### ISSUE TITLE
geolocation.polling.url in GLOBAL deprecated?

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#74]
There is a few locations where geolocation url is specified. HOSTMON, GLOBAL and CCR_CDN. 

Looks like HOSTMON and CCR_CDN shares the same. Although GLOBAL has the hold database maybe? Should this be removed?

**Comment by elsloo** [comment]
geolocation.polling.url is definitely not deprecated, however, it only pertains to Traffic Router (aka CCR) profiles.  I believe what you are seeing is that the parameter is mapped to multiple profiles that do not need the mapping.  You can safely remove the additional, non-Traffic Router profiles from the existing parameter.

To the best of my knowledge, it is not possible to have multiple parameters with the same name, config file, and value, however, you can have multiple parameters with the same name and config file as long as the value is different.  Because of this, it's also possible that you have two different parameters called geolocation.polling.url with different values, mapped separately to a few different profiles.

You will need to determine which profile(s) need to be removed from the geolocation.polling.url parameter that is assigned to your Traffic Router(s), and whether you have an extraneous geolocation.polling.url parameter that is no longer needed and can be deleted.

**Comment by elsloo** [comment]
BTW, specifically, the mapping GLOBAL to this particular parameter is unnecessary.  If there's a bug around removing this mapping, let me know and I'll happily reopen.
