### ISSUE TITLE
Traffic Router not logging request IP correctly when overridden using a header

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#882]
It appears that the IP address in the "chi" field of the access log is always the IP of the machine communicating with Traffic Router. There are special use cases for HTTP delivery services where the client IP is overridden by a request header, and routing decisions are done based on this new IP, not the one connected to Traffic Router. Update logging to reflect this use case.

**Comment by limited** [comment]
Two questions:
1) To clarify, it is currently possible to override the IP used for routing to use an IP from the request header instead of the actual source IP, correct?
2) What will be changing as a result of this issue? Simply a logging field that indicates that chi reflects the IP from the header?

**Comment by dneuman64** [comment]
1) Yes, you can set a "x-mm-client-ip" header.  You could also use a fakeClientIpAddress parameter.  See [here](http://bit.ly/1J235sY )  
2) Yes, currently the chi field in the log contains the actual source IP and not the overriding IP.
