### ISSUE TITLE
TO: Incorrect HTTP response code from API call

### ISSUE THREAD

**Issue by bflanigan** [Comcast/traffic_control#970]
Scenario:
1. Login to Traffic Ops at /api/1.2/user/login with a user that is authenticated through LDAP (ie. not in tm_user table)
2. Make API call to /api/1.2/deliveryservices.json and we get back a HTTP 500
   
   GET /api/1.2/deliveryservices.json HTTP/1.1
   User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
   Host: qa.kabletown.net
   Cookie: mojolicious=eyJhdXRoX2RhdGEiOiIhY2RudG9vbHMiLCJleHBpcmVzIjoxNDUzNTE4NzAyfQ----789ef6d302f16f165cfba10705cf230852e748e5
   Accept: application/json
   
   HTTP/1.1 500 Internal Server Error
   Connection: keep-alive
   Access-Control-Allow-Credentials: true
   Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
   Set-Cookie: mojolicious=eyJhdXRoX2RhdGEiOiIhY2RudG9vbHMiLCJleHBpcmVzIjoxNDUzNTE4OTkyfQ----0aa29283c3c4ca1e36a05001d9afe380d421d626; expires=Sat, 23 Jan 2016 03:16:32 GMT; path=/; HttpOnly
   Cache-Control: no-cache, no-store, max-age=0, must-revalidate
   Date: Fri, 22 Jan 2016 23:16:32 GMT
   Access-Control-Allow-Origin: https://portal-qa.kabletown.net
   Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE
   Content-Length: 93
   Content-Type: application/json
   Server: Mojolicious (Perl)

Should this be a HTTP 401 response code as opposed to a 500 to indicate to the user that it is an insufficient privileges sort of problem ?

**Comment by mitchell852** [comment]
the 500 internal server error is due to a bug that will be fixed in version 1.4.x - https://github.com/Comcast/traffic_control/issues/493

Also, since ldap users are perceived as "privileged" users, they will have access to all delivery services using /api/1.2/deliveryservices.json via https://github.com/Comcast/traffic_control/pull/924

but yes, in most cases if you try to retrieve something that you don't have privileges to see you should get back a 503 forbidden. For example, if you login as a non-ldap user and you try to retrieve api/1.2/deliveryservices/852.json and you don't have access to deliveryservice with id=852, then you'll get back a 503.

**Comment by elsloo** [comment]
Why would an LDAP user have implicit privilege in Traffic Ops versus a local account? That seems silly. Authorization and authentication are two separate things; authentication is authentication regardless if it's local or LDAP. Use authorization via groups/roles, not the source of authentication to determine level of privilege.

**Comment by mitchell852** [comment]
@elsloo - yes, i agree with you. however, we don't have the role necessary at this time to do this. i.e. an "ops read-only" role. so yes, we are currently mixing our metaphors which i believe will be corrected in TO 2.0 - https://github.com/Comcast/traffic_control/wiki/Traffic_Ops_20
