### ISSUE TITLE
Traffic Monitor: Use Local Time for events

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#993]
There might be 2 issues here.
- MST being used to display time in "Status"
- Events shows on local server timezone (instead of client local). For example I had timezone on some Traffic Monitor of EST and some at GMT. The Events would show up at different times. 

In both occasion, I believe it should be client local time.

**Comment by elsloo** [comment]
@smalenfant: In 1.4.0 we moved events into their own log, event.log, separating application logging from state change logging. This new log is similar to our other formats and the timestamp is in seconds since the epoch. This was done via #900.

We have two other timestamps in Traffic Monitor:
1. Timestamp in the Wicket web UI under the event log tab
2. The timestamp in traffic_monitor.log

Both of these are likely using the default locale, which in your case, differs from area to area. We standardize on UTC across the board, so we don't have this issue.

You can correct the timestamp used in traffic_monitor.log yourself via `/opt/traffic_monitor/conf/log4j.properties`, but a code change would be required to allow UTC to be shown in the UI.

My concern is that some users might expect the time to be expressed in their locale, while others may want UTC. It seems that using a local timezone on the OS and UTC in the application logs would produce an inconsistent experience for command line users. When an operations user types "date" they usually expect log lines to correspond with their commands. This same argument could apply, but maybe to a lesser extent, to the web UI.

I'm sort of leaning toward making the timezone displayed in the web UI  configurable (local vs UTC) but might leave log4 as is to ensure we're consistent with the OS.

Thoughts?

**Comment by smalenfant** [comment]
@elsloo I'm using UTC across the board as well. Having it consistent is nice thing to have. When we ingest logs into a platform like Splunk, it normalize to local time for us (depending on the timezone of the client). We ended up with different timestamps because our servers were incorrectly setup. Logs should be UTC. Confusion can be easily resolved by making sure the logs have the Timezone information in them. Which ever format you prefer. ISO 8601?

Having the web UI configuration to show local vs UTC is what I was hoping for which is done on the client side anyway.

**Comment by elsloo** [comment]
We can add the timezone to the application log and web UI. As far as what timezone to use in the web UI, given the direction of things I don't think it's worth it to build a client side tool to change the timezone. I was thinking it would be quick and easy to add a server side configuration parameter that is a boolean that controls whether to show time in localtime or UTC.

If we allow users to select a timezone we'd have to create a UI to allow it, store their settings in a cookie, and then put some JavaScript or something in place to change the timezone based on the user's settings. That seems like overkill for this, especially if we're talking about changing the software/UI for 2.0.

**Comment by smalenfant** [comment]
Local or UTC would be my only choices.
